name: linktree_iqfareez_flutter
description: Flutree project.

publish_to: "none"

version: 3.8.2-web+34

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.0.0
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.3
  dough: ^1.0.1
  fluttertoast: ^8.0.4
  share_plus: ^2.0.3
  package_info_plus: ^1.0.0
  url_strategy: ^0.2.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.2.0
  flutter_lints: ^1.0.4

flutter:
  # uses-material-design: true

  assets:
    - images/logo/
