name: linktree_iqfareez_flutter
description: Flutree project.

publish_to: "none"

version: 3.0.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^1.1.2
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.5.0
  dough: ^0.3.7
  fluttertoast: ^7.1.1
  giffy_dialog: ^1.8.0
  firebase_core: ^0.7.0
  firebase_admob: ^0.11.0+1
  firebase_auth: ^0.20.1
  google_sign_in: ^4.5.9
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0
  image_picker: ^0.6.7+22
  dotted_border: ^1.0.7
  share_plus: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/sample.jpg
    - images/intro.gif
    - images/logo/
    - images/devices.png
    - images/undraw_page_not_found_su7k.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
